### ISSUE TITLE
cz.juzna.intellij.nette.utils.PhpPsiUtil#isLocallyResolvableType uses private API

### ISSUE THREAD

**Issue by neuro159** [nette-intellij/intellij-nette#27]
Will break since today's upcoming EAP

IMO entire method is equal to `((PhpTypedElement)e).getType().isComplete()`

anyway ((PhpTypedElement)e).getType() is the way to get any element type

**Comment by mesour** [comment]
@neuro159 file `cz.juzna.intellij.nette.utils.PhpPsiUtil` is not exists now.
