### ISSUE TITLE
Method 'on*' is undefined

### ISSUE THREAD

**Issue by MartinMystikJonas** [nette-intellij/intellij-nette#34]
For objects implementing SmartObject trait phpStorm inspections shows error for calls to event methods onSomething.

**Comment by mabar** [comment]
I would just use type-safe replacement, it's almost identical and way less magic :)

```
	/** @var array<callable> */
	public array $onFoo = [];

    protected function test(): void
    {
    	foreach ($this->onFoo as $item) {
    		$item();
		}
    }
```

**Comment by MartinMystikJonas** [comment]
That is one way. Or I can add @method annotation. But it would be nice if nette plugin can tell phpStorm this is ok.

**Comment by mesour** [comment]
@MartinMystikJonas anotation `@method` is right way in this case. Because other tools like PhpStan knows it too.
